[project]
id = "examples"
version = "0.1.0"
src = "src"
out = "out"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt = 0
debug = true
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[dep.mach-raylib]
git = "https://github.com/angluca/mach-raylib"
ref = "branch/main"

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"

# -- examples --------------------------------
[artifact.core_basic_window]
kind = "bin"
entry = "core/core_basic_window.mach"
out = "bin/core_basic_window"
targets = ["*"]
link = []
need = []

[artifact.core_basic_screen_manager]
kind = "bin"
entry = "core/core_basic_screen_manager.mach"
out = "bin/core_basic_screen_manager"
targets = ["*"]
link = []
need = []

[artifact.core_input_keys]
kind = "bin"
entry = "core/core_input_keys.mach"
out = "bin/core_input_keys"
targets = ["*"]
link = []
need = []

[artifact.core_input_mouse]
kind = "bin"
entry = "core/core_input_mouse.mach"
out = "bin/core_input_mouse"
targets = ["*"]
link = []
need = []

[artifact.core_scissor_test]
kind = "bin"
entry = "core/core_scissor_test.mach"
out = "bin/core_scissor_test"
targets = ["*"]
link = []
need = []

[artifact.core_2d_camera_mouse_zoom]
kind = "bin"
entry = "core/core_2d_camera_mouse_zoom.mach"
out = "bin/core_2d_camera_mouse_zoom"
targets = ["*"]
link = []
need = []

[artifact.core_2d_camera_split_screen]
kind = "bin"
entry = "core/core_2d_camera_split_screen.mach"
out = "bin/core_2d_camera_split_screen"
targets = ["*"]
link = []
need = []

[artifact.core_2d_camera]
kind = "bin"
entry = "core/core_2d_camera.mach"
out = "bin/core_2d_camera"
targets = ["*"]
link = []
need = []

[artifact.core_3d_camera_first_person]
kind = "bin"
entry = "core/core_3d_camera_first_person.mach"
out = "bin/core_3d_camera_first_person"
targets = ["*"]
link = []
need = []

[artifact.core_3d_picking]
kind = "bin"
entry = "core/core_3d_picking.mach"
out = "bin/core_3d_picking"
targets = ["*"]
link = []
need = []

# -- textures ------------------
# -- text ------------------
# -- shapes ------------------
# -- shaders ------------------
# -- models ------------------
# -- other ------------------
# -- audio ------------------
